config/routes.rb
Simplehire::Application.routes.draw do
  resources :candidates

  resources :candidates
  

  

end

app/models/candidate.rb
class Candidate < ActiveRecord::Base
  enum :stage, [:firstcontact, :teched, :behavioral, :readyforhire, :cold, :warm, :blacklist]

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/candidates_controller.rb
class CandidatesController < ApplicationController
  before_action :set_candidate, only: [:show, :edit, :update, :destroy]

  # GET /candidates
  # GET /candidates.json
  def index
    @candidates = Candidate.all
  end

  # GET /candidates/1
  # GET /candidates/1.json
  def show
  end

  # GET /candidates/new
  def new
    @candidate = Candidate.new
  end

  # GET /candidates/1/edit
  def edit
  end

  # POST /candidates
  # POST /candidates.json
  def create
    
    @candidate = Candidate.new(candidate_params)
    
    # let's save the uploaded file
    uploaded_io = @candidate.resume
    File.open(Rails.root.join('public', 'uploads', uploaded_io.original_filename), 'wb') do |file|
      file.write(uploaded_io.read)
    end
    # and reset the resume to the filepath
    @candidate.resume = uploaded_io.original_filename
    
    respond_to do |format|
      if @candidate.save
        format.html { redirect_to @candidate, notice: 'Candidate was successfully created.' }
        format.json { render action: 'show', status: :created, location: @candidate }
      else
        format.html { render action: 'new' }
        format.json { render json: @candidate.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /candidates/1
  # PATCH/PUT /candidates/1.json
  def update
    # get the whitelisted params now, cause we're going to use it a couple times (and mutate it)
    updateparams = candidate_params
    
        # let's save the uploaded file
    uploaded_io = updateparams[:resume]
    File.open(Rails.root.join('public', 'uploads', uploaded_io.original_filename), 'wb') do |file|
      file.write(uploaded_io.read)
    end
    # and reset the resume to the filepath
    updateparams[:resume] = uploaded_io.original_filename

    respond_to do |format|
      if @candidate.update(updateparams)
        format.html { redirect_to @candidate, notice: 'Candidate was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @candidate.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /candidates/1
  # DELETE /candidates/1.json
  def destroy
    @candidate.destroy
    respond_to do |format|
      format.html { redirect_to candidates_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_candidate
      @candidate = Candidate.find(params[:id])
      
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def candidate_params
      params.require(:candidate).permit(:firstname, :lastname, :email, :phone, :resume, :stage, :last_contact)
    end
  
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/candidates_helper.rb
module CandidatesHelper
end

app/views/candidates/_form.html.erb
<%= form_for(@candidate, :html =>{:class=>"form-horizontal"}) do |f| %>
  <% if @candidate.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@candidate.errors.count, "error") %> prohibited this candidate from being saved:</h2>

      <ul>
      <% @candidate.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label :firstname %><br>
    <%= f.text_field :firstname %>
  </div>
  <div class="form-group">
    <%= f.label :lastname %><br>
    <%= f.text_field :lastname %>
  </div>
  <div class="form-group">
    <%= f.label :email %><br>
    <%= f.text_field :email %>
  </div>
  <div class="form-group">
    <%= f.label :phone %><br>
    <%= f.text_field :phone %>
  </div>
  <div class="form-group">
    <%= f.label :resume %><br>
    <%= f.file_field :resume %>
  </div>
  <div class="form-group">
    <%= f.label :stage %><br>
    <%= f.select(:stage, options_for_select([:firstcontact, :teched, :behavioral, :readyforhire, :cold, :warm, :blacklist])) %>
  </div>
  <div class="form-group">
    <%= f.label :last_contact %><br>
    <%= f.datetime_field :last_contact %>
  </div>
  <div class="actions">
    <%= f.submit 'Go', :class=>'btn btn-submit' %>
  </div>
<% end %>

app/views/candidates/edit.html.erb
<h1>Editing candidate</h1>

<%= render 'form' %>

<%= link_to 'Show', @candidate, class: "btn btn-default" %>
<%= link_to 'Back', candidates_path, class: "btn btn-default" %>

app/views/candidates/index.html.erb
<h1>Listing candidates</h1>

<table class="table table-condensed table-striped">
  <thead>
    <tr>
      <th>Firstname</th>
      <th>Lastname</th>
      <th>Email</th>
      <th>Phone</th>
      <th>Resume</th>
      <th>Stage</th>
      <th>Last contact</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @candidates.each do |candidate| %>
      <tr>
        <td><%= candidate.firstname %></td>
        <td><%= candidate.lastname %></td>
        <td><%= candidate.email %></td>
        <td><%= candidate.phone %></td>
        <td><%= link_to candidate.resume,'/uploads/'+candidate.resume %></td>
        <td><%= candidate.stage %></td>
        <td><%= candidate.last_contact %></td>
        <td><%= link_to 'Show', candidate %></td>
        <td><%= link_to 'Edit', edit_candidate_path(candidate) %></td>
        <td><%= link_to 'Destroy', candidate, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Candidate', new_candidate_path, class: "btn btn-default" %>

app/views/candidates/new.html.erb
<h1>New candidate</h1>

<%= render 'form' %>

<%= link_to 'Back', candidates_path, class: "btn btn-default" %>

app/views/candidates/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Firstname:</strong>
  <%= @candidate.firstname %>
</p>

<p>
  <strong>Lastname:</strong>
  <%= @candidate.lastname %>
</p>

<p>
  <strong>Email:</strong>
  <%= @candidate.email %>
</p>

<p>
  <strong>Phone:</strong>
  <%= @candidate.phone %>
</p>

<p>
  <strong>Resume:</strong>
  <%= @candidate.resume %>
</p>

<p>
  <strong>Stage:</strong>
  <%= @candidate.stage %>
</p>

<p>
  <strong>Last contact:</strong>
  <%= @candidate.last_contact %>
</p>

<%= link_to 'Edit', edit_candidate_path(@candidate), class: "btn btn-default" %>
<%= link_to 'Back', candidates_path, class: "btn btn-default" %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Simplehire</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body class="container">

<%= yield %>

</body>
</html>